image: maven:3.3-jdk-8

stages:
  - build

build:
  stage: build
  tags: ["runner:docker", "size:large"]
  script:
    - apt-get update || echo debian jessie is old
    - apt-get install -y --no-install-recommends awscli
    - mvn install
    - aws s3 cp --region us-east-1 --sse AES256 --acl bucket-owner-full-control target/releases/*.jar s3://dd-ci-artefacts-build-stable/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/
    - aws s3 cp --region us-east-1 --sse AES256 --acl bucket-owner-full-control target/releases/*.jar s3://dd-ci-persistent-artefacts-build-stable/$CI_PROJECT_NAME/
