version: '2'
services:
  vault:
    image: vault:1.1.2
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root-token
  kafka_SASL_PLAINTEXT:
    image: ultimate/kafka-sasl-plain-vault
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root-token